### ISSUE TITLE
Checking that we can pull requests and track our agreements via Github

### ISSUE THREAD

**Issue by samanthajdalton** [JordiZamora/Machine-LearningDLZ#1]
Hi,

I thought we could assign tasks via GIthub with issue tickets.  Wanted to see if this worked for you both.

**Comment by JordiZamora** [comment]
Yes. It works! And an email for each action is sent. So we can use this system to keep track of decissions taken and open problems, isn't it?

**Comment by samanthajdalton** [comment]
Agreed, we can track all tasks we decide to assign and reasons for our decisions, so documentation will be easier.
